name: BlockCmdPE
main: Vaivez66\BlockCmdPE\BlockCmd
version: 1.0.0
api: [1.12.0, 2.0.0]
load: POSTWORLD
authors: [Vaivez66]
description: "Block some commands!"
permissions:
  block.cmd.pe.bypass:
    description: 'Permission to bypass from blocking'
    default: op
